### ISSUE TITLE
MultipleItemRvAdapter 自定义BaseViewHolder出现强转异常的问题

### ISSUE THREAD

**Issue by K-Hector** [chaychan/MultipleItemRvAdapter#9]
异常信息：
java.lang.ClassCastException: com.chad.library.adapter.base.BaseViewHolder cannot be cast to adapter.itemprovider.SmallContentViewHolder
        at adapter.itemprovider.IPCommercialDetailSmallContent.convert(IPCommercialDetailSmallContent.java:21)
        at com.chad.library.adapter.base.MultipleItemRvAdapter.convert(MultipleItemRvAdapter.java:70)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:951)
        at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:68)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6476)

这是其中一种类型的
![image](https://user-images.githubusercontent.com/20419467/42503344-0296e304-846b-11e8-8bc2-7941fa4f0fc4.png)

这是另一种类型的：
![image](https://user-images.githubusercontent.com/20419467/42503275-e49a729e-846a-11e8-9f05-3b00f0a62e9b.png)

适配器代码类型指定为了BaseViewHolder：
![image](https://user-images.githubusercontent.com/20419467/42503421-34334b6e-846b-11e8-949a-e7d7fa26e5f9.png)

断点后异常出现的位置是在MultipleItemRvAdapter中的convert()方法中：
![image](https://user-images.githubusercontent.com/20419467/42503660-cfeb3094-846b-11e8-8ced-14c099c67737.png)

感觉这样强转一定会出错的吧？

**Comment by K-Hector** [comment]
问题解决了，重写onCreateDefViewHolder(ViewGroup parent, int viewType)方法,，反射用的字节码对象应该拿BaseItemProvider上的

    @Override
    protected V onCreateDefViewHolder(ViewGroup parent, int viewType) {
        int layoutId = mLayoutResId;
        if (getMultiTypeDelegate() != null) {
            layoutId = getMultiTypeDelegate().getLayoutId(viewType);
        }
        View view = getItemView(layoutId, parent);

        Class temp = mItemProviders.get(viewType).getClass();
        Class z = null;
        while (z == null && null != temp) {
            z = getInstancedGenericKClass(temp);
            temp = temp.getSuperclass();
        }
        V k;
        // 泛型擦除会导致z为null
        if (z == null) {
            k = (V) new BaseViewHolder(view);
        } else {
            k = createGenericKInstance(z, view);
        }
        return k != null ? k : (V) new BaseViewHolder(view);
    }

    protected Class getInstancedGenericKClass(Class z) {
        Type type = z.getGenericSuperclass();
        if (type instanceof ParameterizedType) {
            Type[] types = ((ParameterizedType) type).getActualTypeArguments();
            for (Type temp : types) {
                if (temp instanceof Class) {
                    Class tempClass = (Class) temp;
                    if (BaseViewHolder.class.isAssignableFrom(tempClass)) {
                        return tempClass;
                    }
                } else if (temp instanceof ParameterizedType) {
                    Type rawType = ((ParameterizedType) temp).getRawType();
                    if (rawType instanceof Class && BaseViewHolder.class.isAssignableFrom((Class<?>) rawType)) {
                        return (Class<?>) rawType;
                    }
                }
            }
        }
        return null;
    }

    protected V createGenericKInstance(Class z, View view) {
        try {
            Constructor constructor;
            // inner and unstatic class
            if (z.isMemberClass() && !Modifier.isStatic(z.getModifiers())) {
                constructor = z.getDeclaredConstructor(getClass(), View.class);
                constructor.setAccessible(true);
                return (V) constructor.newInstance(this, view);
            } else {
                constructor = z.getDeclaredConstructor(View.class);
                constructor.setAccessible(true);
                return (V) constructor.newInstance(view);
            }
        } catch (NoSuchMethodException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (InvocationTargetException e) {
            e.printStackTrace();
        }
        return null;
    }
